### ISSUE TITLE
Probably a trivial bug in the code comment

### ISSUE THREAD

**Issue by katori-ouo** [yluo42/FRA-RIR#5]
In line 255 of [FRAM-RIR.py](https://github.com/tencent-ailab/FRA-RIR/blob/fram_rir/FRAM-RIR.py): `# [nmic, nsrc, 1 + sr*2]`
`sr` may represent the sample rate, as the code in line 110: `def FRA_RIR_ADHOC(mic_arch, sr=16000, rt60=None, room_dim=None,...`
Should the size of `dist` and `reflect_ratio` be `# [nmic, nsrc, 1 + image]` after `torch.cat()`?
I'm confused with this and want to know which is true?
> I print the size for verfication:
![image](https://github.com/tencent-ailab/FRA-RIR/assets/55440795/7345931e-12c8-4266-b4b5-aebd4cdca8e5)

**Comment by Moplast** [comment]
Hi katori, thanks for your interest in this work. 

I think the comment in line 255 of FRAM-RIR.py: 
`# [nmic, nsrc, 1 + sr*2] `
should be 
`# [nmic, nsrc, 1 + nimage] ` 

Thanks for pointing out the comment bug, since it does not affect the code implementation, we will fix the comment in a future version.

**Comment by katori-ouo** [comment]
Thanks for answering.
